/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lib/cgi_servlet.h"

int handle_list (struct request *req, struct response *resp);
int handle_asdf (struct request *req, struct response *resp);

int main(int argc, char *argv[]) 
{

	struct url_mapping map[] = { 
		{"/do.list", handle_list},
		{"/do.asdf", handle_asdf},
		{"/do.login", handle_list},
		{"/do.qwer", handle_asdf},
		{"/do.zxcv", handle_list}
	};

	struct config conf = {
		NULL
		/*default_error_html = "error.html";*/
	};

	cgi_servlet_init (&conf, &map, 5, NULL);

}

int handle_list (struct request *req, struct response *resp) {

	if (cgi_request_get_parameter (req, "detail") != NULL) {
		resp->html = strdup ("html/detail.html");
	} else {
		resp->html = strdup ("html/teste.html");
	}

	cgi_response_add_cookie (resp, "nome", "valor", NULL, NULL, NULL, 0);
	
	return 0;
}

int handle_asdf (struct request *req, struct response *resp) {

	printf ("handle_asdf( )\n");

	resp->html = strdup ("html/asdf.html");
	
	return 0;
}
